---
language: python
services: docker

env:
  global:
    - ROLE_NAME: logwatch

install:
  - pip install molecule docker

script:
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
