---
language: python
services: docker

env:
  global:
    - ROLE_NAME: logwatch

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $ROLE_NAME apiotrowski312.$ROLE_NAME
  - cd apiotrowski312.$ROLE_NAME

script:
  # Run tests.
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/